import { Product } from '../features/products/products.interfaces'

export const ProductsInitialState: Product[] = [
  {
    id: 1,
    name: 'Torta 1',
    description: 'Opis torte 1',
    price: 300,
    type: 'torta',
    ingredients: 'Mleko, šećer, jaja',
    pic: '/products/Cake1.jpg',
  },
  {
    id: 2,
    name: 'Torta 2',
    description: 'Opis torte 2',
    price: 300,
    type: 'torta',
    ingredients: 'Mleko, šećer, jaja',
    pic: '/products/Cake2.jpg',
  },
  {
    id: 3,
    name: 'Torta 3',
    description: 'Opis torte 3',
    price: 300,
    type: 'torta',
    ingredients: 'Mleko, šećer, jaja',
    pic: '/products/Cake3.jpg',
  },
  {
    id: 4,
    name: 'Torta 4',
    description: 'Opis torte 4',
    price: 300,
    type: 'torta',
    ingredients: 'Mleko, šećer, jaja',
    pic: '/products/Cake4.jpg',
  },
  {
    id: 5,
    name: 'Torta 5',
    description: 'Opis torte 5',
    price: 300,
    type: 'torta',
    ingredients: 'Mleko, šećer, jaja',
    pic: '/products/Cake5.jpg',
  },
  {
    id: 6,
    name: 'Torta 6',
    description: 'Opis torte 6',
    price: 300,
    type: 'torta',
    ingredients: 'Mleko, šećer, jaja',
    pic: '/products/Cake6.jpg',
  },

  {
    id: 7,
    name: 'Kolač 1',
    description: 'Opis torte 1',
    price: 300,
    type: 'kolač',
    ingredients: 'Mleko, šećer, jaja',
    pic: '/products/Cookie1.jpg',
  },
  {
    id: 8,
    name: 'Kolač 2',
    description: 'Opis kolača 2',
    price: 300,
    type: 'kolač',
    ingredients: 'Mleko, šećer, jaja',
    pic: '/products/Cookie2.jpg',
  },
  {
    id: 9,
    name: 'Kolač 3',
    description: 'Opis kolača 3',
    price: 300,
    type: 'kolač',
    ingredients: 'Mleko, šećer, jaja',
    pic: '/products/Cookie3.jpg',
  },
  {
    id: 10,
    name: 'Kolač 4',
    description: 'Opis kolača 4',
    price: 300,
    type: 'kolač',
    ingredients: 'Mleko, šećer, jaja',
    pic: '/products/Cookie4.jpg',
  },
  {
    id: 11,
    name: 'Kolač 5',
    description: 'Opis kolača 5',
    price: 300,
    type: 'kolač',
    ingredients: 'Mleko, šećer, jaja',
    pic: '/products/Cookie5.jpg',
  },
  {
    id: 12,
    name: 'Kolač 6',
    description: 'Opis kolača 6',
    price: 300,
    type: 'kolač',
    ingredients: 'Mleko, šećer, jaja',
    pic: '/products/Cookie6.jpg',
  },
]
